version: "3.7"
services:
  spark-master:
    image: spark-base
    container_name: spark-master
    hostname: spark-master
    ports:
        - "18080:18080"
        - "8888:8888"
        - "8080:8080"
        - "8088:8088"
        - "7077:7077"
        - "50070:50070"
        - "8032:8032"
        - "8020:8020"
    networks: 
      spark-network:
        ipv4_address: 10.5.0.2
    volumes:
       - hdfs_data:/data
       - ./notebooks:/tmp/notebooks
    env_file: ./config/spark-master.env
    environment:
      - "SPARK_LOCAL_IP=spark-master"
    entrypoint: ["/tmp/config/entrypoint_master.sh"]
  spark-worker-1:
    image: spark-base
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    env_file: ./config/spark-worker.env
    environment:
      - "SPARK_LOCAL_IP=spark-worker-1"
    entrypoint: ["/tmp/config/entrypoint_worker.sh"]
    networks: 
      spark-network:
        ipv4_address: 10.5.0.3
    volumes:
       - hdfs_data:/data
       - ./notebooks:/tmp/notebooks
  spark-worker-2:
    image: spark-base
    container_name: spark-worker-2
    hostname: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    env_file: ./config/spark-worker.env
    environment:
      - "SPARK_LOCAL_IP=spark-worker-2"
    entrypoint: ["/tmp/config/entrypoint_worker.sh"]
    networks: 
      spark-network:
        ipv4_address: 10.5.0.4
    volumes:
       - hdfs_data:/data
       - ./notebooks:/tmp/notebooks
  spark-worker-3:
    image: spark-base
    container_name: spark-worker-3
    hostname: spark-worker-3
    depends_on:
      - spark-master
    ports:
      - "8083:8081"
    env_file: ./config/spark-worker.env
    environment:
      - "SPARK_LOCAL_IP=spark-worker-3"
    entrypoint: ["/tmp/config/entrypoint_worker.sh"]
    networks: 
      spark-network:
        ipv4_address: 10.5.0.5
    volumes:
        - hdfs_data:/data
        - ./notebooks:/tmp/notebooks

volumes:
  hdfs_data:        
networks:
  spark-network:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 10.5.0.0/16
